### ISSUE TITLE
Cordova-second-webview not working

### ISSUE THREAD

**Issue by cwkerk** [kunder-lab/cl.kunder.webview#16]
I try to use "cordova-second-webview" plugin to create extra page for new webview by code below:

mainApp.browseWeb = function(address){
        if(navigator.connection.type != Connection.NONE){
                var browseWebView = new webview();
                browseWebView.Show("https://angularjs.org","_blank", function(){alert("WebView Success");}, function(){alert("WebView Failure");}, true);
               this.WebViews.push(browseWebView);
               alert('The web view is created');
    }
    else alert('Browse error : No network connection');
}

However, I don't get it work even to open a webview. May I know why and how to fix it?

**Comment by sebalagos90** [comment]
Hi @cwkerk. 
The "Show" method only accepts 4 parameters like this:
webview.Show(YOUR_URL [string], SUCCESS_FUNCTION [function], ERROR_FUNCTION [function], SHOULD_SHOW_LOADING [boolean]);

Best regards!

**Comment by cwkerk** [comment]
Thank you for reply.
However, after I change into "browseWebView.Show("https://angularjs.org",function(){alert("WebView Success");}, function(){alert("WebView Failure");}, true);", it still not working

**Comment by cwkerk** [comment]
I wonder why the following code doesn't work:

mainApp.browseWeb = function(address){
    if(navigator.connection.type != Connection.NONE){
        var browseWebView = new webview();
        browseWebView.Show(address, function(){alert("WebView Success");}, function(){alert("WebView Failure");}, true);
        alert('The web view is created');
    }
    else alert('Browse error : No network connection');
}

**Comment by sebalagos90** [comment]
What operating system did you try your code?
The mainApp.browseWeb is called in your code?

**Comment by cwkerk** [comment]
iphone 6s plus.
May I know is this plugin work for all ios version?

**Comment by sebalagos90** [comment]
We use it daily and we don't have issues.
Please let me check it out

**Comment by cwkerk** [comment]
May I have our example code for this plugin?
Just for reference, maybe I may find the bug with that help.

**Comment by sebalagos90** [comment]
I did create a new ionic project and wrote the following code:
$scope.click = function(){
    document.addEventListener('deviceready', function(){
      webview.Show('http://www.google.cl', function(){alert("WebView Success");}, function(){alert("WebView Failure");}, true);
    }, false);
  };
With or without device ready event works fine.

**Comment by cwkerk** [comment]
I see.
I wonder if this plugin only works with ionic framework? 
I didn't use it since it is quite heavy to build app in my macbook.

**Comment by arturokunder** [comment]
@cwkerk 
It should work with any framework.
If you [checkout the js code](https://github.com/kunder-lab/cl.kunder.webview/blob/master/www/webViewPlugin.js), you can see that there isnt references to any framework.

Maybe your problem is your are constructing a `webview` object, but `webview` class only has static methods

Look at @sebalagos90 code. It uses `webview.Show()` directly.
But in your code:

``` js
var browseWebView = new webview();  
browseWebView.Show(address, function(){alert("WebView Success");}, function(){alert("WebView Failure");}, true);
```

**Comment by cwkerk** [comment]
By the way, how can I make multiple webviews using this plugin?

**Comment by arturokunder** [comment]
@cwkerk you can make multiple webviews on `iOS` but not in `Android`
In order to make it work on `Android`, you will need to change the code a little because there are some `static` variables as described in #3
