### ISSUE TITLE
[IOS][Android] how to set width and height to the new webview

### ISSUE THREAD

**Issue by ibrahim-sakr** [kunder-lab/cl.kunder.webview#17]
as the title show 
I want to create another function called for example resize(width, height)
to control the width and the height of the new webview.

How we do this, any idea ????

**Comment by arturokunder** [comment]
Hi @ibrahimsaqr 
The webview for now is full screen. You'll have to make a PR with this change in the native code

**Comment by JSeligsohn** [comment]
@ibrahim-sakr Did you ever figure this out?
