### ISSUE TITLE
iOS internal url

### ISSUE THREAD

**Issue by willicom2000** [kunder-lab/cl.kunder.webview#34]
Hi! I am trying to open an internal url in a different webview for ios platform. I wrote:

webview.Show("file:///Staging/www/tam.html");

But i got the error:

File not exists.

What i was doing wrong? Thanks for your patient!

**Comment by arturokunder** [comment]
Hi @willicom2000!
You can put only the relative path:
```js
webview.Show('tam.html')
```

The file url prefix (`file://`) is added automatically by the plugin if it's neccesary ([Android example](https://github.com/kunder-lab/cl.kunder.webview/blob/master/src/android/cl/kunder/webview/WebViewActivity.java#L37))

**Comment by willicom2000** [comment]
Hi! I tried 

webview.Show('tam.html')

And not worked, the problem is only for iOS. Android works fine! tam.html is a local ".html", in the Staging location.
