### ISSUE TITLE
the plugin automatically adds the prefix file:///android_asset/www/

### ISSUE THREAD

**Issue by UniqueAlex** [kunder-lab/cl.kunder.webview#43]
when i want to create a new webview with this plugin and call show() function with a URL like https://www.google.com.

the app will show a error alert "network error.(file:///android_asset/www/https://www.google.com)", could you give some advice why the prefix file:///android_asset/www/ will added front of the URL automatically?

**Comment by davidgovea** [comment]
@UniqueAlex we're seeing the same issue. I have a PR #44 out, but you can also go back to `v2.6.0` if you are not using the encrypted file feature.

**Comment by kiwi-josh** [comment]
Any case of getting a review and merge on this one? We are also experiencing this

**Comment by arturokunder** [comment]
Hi! PR #44 is already merged.
We published as version 2.7.1
Thanks @davidgovea for the hotfix!
